@extends ('layouts.master')
    
    @section ('head.title')

        Điều khoản sử dụng

    @stop
    @include('partials.navbar')
    @section ('body.content')
		<body>
			<div class="container" style="padding-top: 20px;padding-bottom: 20px;">
				<h2 style="font-family: Arial Italic;"> Điều khoản sử dụng</h2>
				<p style="font-family: Arial Italic;"><strong style="font-family: Arial Italic;">Về tài khoản sử dụng(TKSD)</strong>: Khi đăng kí tài khoản <strong style="font-family: Arial Italic;">Beestudy</strong> ID, người sử dụng (NSD) phải cung cấp đầy đủ và chính xác thông tin về Tên, Email, Số điện thoại, Mật khẩu. Đây là những thông tin bắt buộc liên quan tới việc hỗ trợ NSD trong quá trình sử dụng dịch vụ. Vì vậy khi có những rủi ro, mất mát sau này, chúng tôi chỉ tiếp nhận những trường hợp điền đúng và đầy đủ những thông tin trên. Những trường hợp điền thiếu thông tin hoặc thông tin sai sự thật sẽ không được giải quyết. Những thông tin này sẽ được dùng làm căn cứ để hỗ trợ giải quyết. <br>
				Nếu NSD cung cấp bất kỳ thông tin nào không trung thực hoặc không chính xác, hoặc nếu chúng tôi có cơ sở để nghi ngờ rằng thông tin đó không phải là thông tin trung thực hoặc không chính xác, chúng tôi có quyền đình chỉ tạm thời để xác minh hoặc chấm dứt việc sử dụng Tài khoản của NSD và từ chối toàn bộ việc sử dụng Dịch vụ (hoặc bất kỳ phần nào của Dịch vụ) tại thời điểm hiện tại hoặc sau này mà không phải chịu bất cứ trách nhiệm nào đối với NSD.</p>
				<p style="font-family: Arial Italic;"> <strong style="font-family: Arial Italic;">Mật khẩu của tài khoản(MKTK)</strong>: Trong phần quản lý tài khoản, đối với một tài khoản, NSD sẽ có một mật khẩu. Mật khẩu được sử dụng để đăng nhập vào các website và các dịch vụ trong hệ thống của <strong style="font-family: Arial Italic;">Beestudy</strong>. NSD có trách nhiệm phải tự mình bảo quản mật khẩu, nếu mật khẩu bị lộ ra ngoài dưới bất kỳ hình thức nào, <strong style="font-family: Arial Italic;">Beestudy</strong> sẽ không chịu trách nhiệm về mọi tổn thất phát sinh. <br> Tuyệt đối không sử dụng bất kỳ chương trình, công cụ hay hình thức nào khác để can thiệp vào các dịch vụ trong hệ thống <strong style="font-family: Arial Italic;">Beestudy</strong>. Mọi vi phạm khi bị phát hiện sẽ bị xóa tài khoản và có thể xử lý theo quy định của pháp luật. <br> Nghiêm cấm việc phát tán, truyền bá hay cổ vũ cho bất kỳ hoạt động nào nhằm can thiệp, phá hoại hay xâm nhập vào dữ liệu của các dịch vụ, khóa học trong hệ thống của <strong style="font-family: Arial Italic;">Beestudy</strong>. Nghiêm cấm việc sử dụng chung tài khoản. Việc trên 2 người cùng sử dụng chung một tài khoản khi bị phát hiện sẽ bị xóa tài khoản ngay lập tức. <br> Trong những trường hợp bất khả kháng như chập điện, hư hỏng phần cứng, phần mềm, hoặc do thiên tai .v.v. NSD phải chấp nhận những thiệt hại nếu có. <br> Tuyệt đối không bàn luận về các vấn đề chính trị, kỳ thị tôn giao, kỳ thị sắc tộc. Không có những hành vi, thái độ làm tổn hại đến uy tín của các sản phẩm, dịch vụ trong hệ thống <strong style="font-family: Arial Italic;">Beestudy</strong> dưới bất kỳ hình thức nào, phương thức nào. Mọi vi phạm sẽ bị tước bỏ mọi quyền lợi liên quan đối với tài khoản hoặc xử lý trước pháp luật nếu cần thiết. Mọi thông tin cá nhân của NSD sẽ được chúng tôi bảo mật, không tiết lộ ra ngoài. Chúng tôi không bán hay trao đổi những thông tin này với bất kỳ một bên thứ ba nào khác. Như trên đã nói, mọi thông tin đăng ký của NSD sẽ được bảo mật, nhưng trong trường hợp cơ quan chức năng yêu cầu, chúng tôi sẽ buộc phải cung cấp những thông tin này cho các cơ quan chức năng. <br> <strong style="font-family: Arial Italic;">Beestudy</strong> có toàn quyền xóa, sửa chữa hay thay đổi các dữ liệu, thông tin tài khoản của NSD trong các trường hợp người đó vi phạm những qui định kể trên mà không cần sự đồng ý của người sử dụng. <br> <strong style="font-family: Arial Italic;">Beestudy</strong> có thể thay đổi, bổ sung hoặc sửa chữa thỏa thuận này bất cứ lúc nào và sẽ công bố rõ trên Website hoặc các kênh truyền thông chính thức khác.</p>
			</div>
		</body>
    @include('partials.footer')
    @stop